CREATE TABLE IF NOT EXISTS forums (
  id SERIAL NOT NULL PRIMARY KEY,
  posts INTEGER DEFAULT 0,
  slug CITEXT COLLATE "ucs_basic" UNIQUE,
  threads INTEGER DEFAULT 0,
  title TEXT NOT NULL,
  nickname CITEXT COLLATE "ucs_basic" REFERENCES "users"(nickname) ON DELETE CASCADE,
  user_id INTEGER NOT NULL  REFERENCES "users"(id) ON DELETE CASCADE
);